<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LabGTI-PC" name="controller.InserirBancoTest" tests="5" failures="0" timestamp="9 Jul 2015 13:30:19 GMT" time="34.078" errors="1">
  <testcase name="TestListarContatosPagina" time="0.171" classname="controller.InserirBancoTest">
    <error type="java.lang.AssertionError" message="expected:&lt;[Henrique, Pro, Jarbas]&gt; but was:&lt;[model.Pessoa@840baa, model.Pessoa@101da1e]&gt;">
      <![CDATA[java.lang.AssertionError: expected:<[Henrique, Pro, Jarbas]> but was:<[model.Pessoa@840baa, model.Pessoa@101da1e]>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
	at controller.InserirBancoTest.TestListarContatosPagina(InserirBancoTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- TestListarContatosPagina -->
  <testcase name="TestInserirNoBancoDoisTelefones" time="0.033" classname="controller.InserirBancoTest"/>
  <testcase name="TestChamadaPaginaHome" time="0.008" classname="controller.InserirBancoTest"/>
  <testcase name="TestInserirChamandoInterface" time="33.628" classname="controller.InserirBancoTest"/>
  <testcase name="TestInserirNoBanco" time="0.238" classname="controller.InserirBancoTest"/>
</testsuite> <!-- controller.InserirBancoTest -->
